//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace UsedBooks.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pictrue
    {
        public int PictrueID { get; set; }
        public int BookID { get; set; }
        public string Desn { get; set; }
        public string Url { get; set; }
        public string PictrueType { get; set; }
        public Nullable<int> IsShow { get; set; }
        public string Remark { get; set; }
    
        public virtual Book Book { get; set; }
    }
}
