//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace UsedBooks.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookNeed
    {
        public int BookNID { get; set; }
        public string price { get; set; }
        public string BName { get; set; }
        public string Phone { get; set; }
        public System.DateTime DataTime { get; set; }
        public int UserID { get; set; }
    
        public virtual User User { get; set; }
    }
}
